using NfsCore.Reflection.Abstract;

namespace NfsCore.Support.Underground2.Class
{
    public partial class CarTypeInfo
    {
        /// <summary>
        /// Casts all attributes from this object to another one.
        /// </summary>
        /// <param name="collectionName">CollectionName of the new created object.</param>
        /// <returns>Memory casted copy of the object.</returns>
        public override Collectable MemoryCast(string collectionName)
        {
            var result = new CarTypeInfo(collectionName, Database)
            {
                _spoiler = _spoiler,
                _mirrors = _mirrors,
                UsageType = UsageType,
                MemoryType = MemoryType,
                IsSkinnable = IsSkinnable,
                ManufacturerName = ManufacturerName,
                _defaultBasePaint = _defaultBasePaint,
                _defaultBasePaint2 = _defaultBasePaint2,
                _isSuv = _isSuv,
                HeadlightFOV = HeadlightFOV,
                PadHighPerformance = PadHighPerformance,
                NumAvailableSkinNumbers = NumAvailableSkinNumbers,
                WhatGame = WhatGame,
                ConvertibleFlag = ConvertibleFlag,
                WheelOuterRadius = WheelOuterRadius,
                WheelInnerRadiusMin = WheelInnerRadiusMin,
                WheelInnerRadiusMax = WheelInnerRadiusMax,
                Padding0 = Padding0,
                HeadlightPositionX = HeadlightPositionX,
                HeadlightPositionY = HeadlightPositionY,
                HeadlightPositionZ = HeadlightPositionZ,
                HeadlightPositionW = HeadlightPositionW,
                DriverRenderingOffsetX = DriverRenderingOffsetX,
                DriverRenderingOffsetY = DriverRenderingOffsetY,
                DriverRenderingOffsetZ = DriverRenderingOffsetZ,
                DriverRenderingOffsetW = DriverRenderingOffsetW,
                SteeringWheelRenderingX = SteeringWheelRenderingX,
                SteeringWheelRenderingY = SteeringWheelRenderingY,
                SteeringWheelRenderingZ = SteeringWheelRenderingZ,
                SteeringWheelRenderingW = SteeringWheelRenderingW,
                UnknownVectorValX = UnknownVectorValX,
                UnknownVectorValY = UnknownVectorValY,
                UnknownVectorValZ = UnknownVectorValZ,
                UnknownVectorValW = UnknownVectorValW,
                MaxInstances1 = MaxInstances1,
                MaxInstances2 = MaxInstances2,
                MaxInstances3 = MaxInstances3,
                MaxInstances4 = MaxInstances4,
                MaxInstances5 = MaxInstances5,
                KeepLoaded1 = KeepLoaded1,
                KeepLoaded2 = KeepLoaded2,
                KeepLoaded3 = KeepLoaded3,
                KeepLoaded4 = KeepLoaded4,
                KeepLoaded5 = KeepLoaded5,
                Padding1 = Padding1,
                MinTimeBetweenUses1 = MinTimeBetweenUses1,
                MinTimeBetweenUses2 = MinTimeBetweenUses2,
                MinTimeBetweenUses3 = MinTimeBetweenUses3,
                MinTimeBetweenUses4 = MinTimeBetweenUses4,
                MinTimeBetweenUses5 = MinTimeBetweenUses5,
                AvailableSkinNumbers01 = AvailableSkinNumbers01,
                AvailableSkinNumbers02 = AvailableSkinNumbers02,
                AvailableSkinNumbers03 = AvailableSkinNumbers03,
                AvailableSkinNumbers04 = AvailableSkinNumbers04,
                AvailableSkinNumbers05 = AvailableSkinNumbers05,
                AvailableSkinNumbers06 = AvailableSkinNumbers06,
                AvailableSkinNumbers07 = AvailableSkinNumbers07,
                AvailableSkinNumbers08 = AvailableSkinNumbers08,
                AvailableSkinNumbers09 = AvailableSkinNumbers09,
                AvailableSkinNumbers10 = AvailableSkinNumbers10,
                DefaultSkinNumber = DefaultSkinNumber,
                Padding2 = Padding2,
                AI_CAMERA_BUMPER = AI_CAMERA_BUMPER.PlainCopy(),
                AI_CAMERA_CLOSE = AI_CAMERA_CLOSE.PlainCopy(),
                AI_CAMERA_DRIFT = AI_CAMERA_DRIFT.PlainCopy(),
                AI_CAMERA_DRIVER = AI_CAMERA_DRIVER.PlainCopy(),
                AI_CAMERA_FAR = AI_CAMERA_FAR.PlainCopy(),
                AI_CAMERA_HOOD = AI_CAMERA_HOOD.PlainCopy(),
                PLAYER_CAMERA_BUMPER = PLAYER_CAMERA_BUMPER.PlainCopy(),
                PLAYER_CAMERA_CLOSE = PLAYER_CAMERA_CLOSE.PlainCopy(),
                PLAYER_CAMERA_DRIFT = PLAYER_CAMERA_DRIFT.PlainCopy(),
                PLAYER_CAMERA_DRIVER = PLAYER_CAMERA_DRIVER.PlainCopy(),
                PLAYER_CAMERA_FAR = PLAYER_CAMERA_FAR.PlainCopy(),
                PLAYER_CAMERA_HOOD = PLAYER_CAMERA_HOOD.PlainCopy(),
                BASE_BRAKES = BASE_BRAKES.PlainCopy(),
                BASE_ENGINE = BASE_ENGINE.PlainCopy(),
                BASE_RPM = BASE_RPM.PlainCopy(),
                BASE_SUSPENSION = BASE_SUSPENSION.PlainCopy(),
                BASE_TIRES = BASE_TIRES.PlainCopy(),
                BASE_TRANSMISSION = BASE_TRANSMISSION.PlainCopy(),
                BASE_TURBO = BASE_TURBO.PlainCopy(),
                DRIFT_ADD_CONTROL = DRIFT_ADD_CONTROL.PlainCopy(),
                ECAR = ECAR.PlainCopy(),
                PVEHICLE = PVEHICLE.PlainCopy(),
                PRO_ECU = PRO_ECU.PlainCopy(),
                PRO_RPM = PRO_RPM.PlainCopy(),
                PRO_TRANSMISSION = PRO_TRANSMISSION.PlainCopy(),
                STREET_ECU = STREET_ECU.PlainCopy(),
                STREET_RPM = STREET_RPM.PlainCopy(),
                STREET_TRANSMISSION = STREET_TRANSMISSION.PlainCopy(),
                TOP_BRAKES = TOP_BRAKES.PlainCopy(),
                TOP_ECU = TOP_ECU.PlainCopy(),
                TOP_ENGINE = TOP_ENGINE.PlainCopy(),
                TOP_NITROUS = TOP_NITROUS.PlainCopy(),
                TOP_RPM = TOP_RPM.PlainCopy(),
                TOP_SUSPENSION = TOP_SUSPENSION.PlainCopy(),
                TOP_TIRES = TOP_TIRES.PlainCopy(),
                TOP_TRANSMISSION = TOP_TRANSMISSION.PlainCopy(),
                TOP_TURBO = TOP_TURBO.PlainCopy(),
                TOP_WEIGHT_REDUCTION = TOP_WEIGHT_REDUCTION.PlainCopy(),
                WHEEL_FRONT_LEFT = WHEEL_FRONT_LEFT.PlainCopy(),
                WHEEL_FRONT_RIGHT = WHEEL_FRONT_RIGHT.PlainCopy(),
                WHEEL_REAR_LEFT = WHEEL_REAR_LEFT.PlainCopy(),
                WHEEL_REAR_RIGHT = WHEEL_REAR_RIGHT.PlainCopy(),
                CARSKIN01 = CARSKIN01.PlainCopy(),
                CARSKIN02 = CARSKIN02.PlainCopy(),
                CARSKIN03 = CARSKIN03.PlainCopy(),
                CARSKIN04 = CARSKIN04.PlainCopy(),
                CARSKIN05 = CARSKIN05.PlainCopy(),
                CARSKIN06 = CARSKIN06.PlainCopy(),
                CARSKIN07 = CARSKIN07.PlainCopy(),
                CARSKIN08 = CARSKIN08.PlainCopy()
            };

            return result;
        }
    }
}